### ISSUE TITLE
My benchmark result

### ISSUE THREAD

**Issue by aquapi** [npmstudy/elysia-vs-fastify-benchmark#1]
Here is my benchmark result using a different benchmark suite.
https://github.com/bit-js/bench/blob/main/frameworks/results.md
![image](https://github.com/npmstudy/elysia-vs-fastify-benchmark/assets/87530663/f1d5ae13-e11f-42f5-aacf-7a11ce6000f7)

**Comment by npmstudy** [comment]
you need make fastify logging = false, and use cluster mode. if not , maybe the result is not fair

**Comment by aquapi** [comment]
I will change it and publish the result here

**Comment by aquapi** [comment]
It get slightly faster but not enough to beat any Bun frameworks.
![image](https://github.com/npmstudy/elysia-vs-fastify-benchmark/assets/87530663/c022cf47-2c72-4970-b789-74c77c30e26c)

DB query is basically connecting to an SQLite database and get the top 50 items in a table.
I use `better-sqlite3` for Fastify

**Comment by npmstudy** [comment]
use this repo code and benckmark , maybe wo can reach an agreement

**Comment by npmstudy** [comment]
i see your code , no cluster is required.

**Comment by aquapi** [comment]
@npmstudy Can you create a script so I can run that and get all the results out instead of running each of the server?
